{% set name = "accelerate" %}
{% set version = "0.32.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/accelerate-{{ version }}.tar.gz
  sha256: ebd60cf05a43c6a23b68360d1861403bf74d8c8f9a2287b1947c1d194d686769

build:
  number: 0
  noarch: python
  entry_points:
    - accelerate=accelerate.commands.accelerate_cli:main
    - accelerate-config=accelerate.commands.config:main
    - accelerate-estimate-memory=accelerate.commands.estimate:main
    - accelerate-launch=accelerate.commands.launch:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8.0
  run:
    - python >=3.8.0
    - numpy >=1.17,<2.0.0
    - packaging >=20.0
    - psutil
    - pyyaml
    - pytorch >=1.10.0
    - huggingface_hub
    - safetensors >=0.3.1

test:
  imports:
    - accelerate
  commands:
    - pip check
    - accelerate --help
    - accelerate-config --help
    - accelerate-launch --help
    - accelerate-estimate-memory --help
  requires:
    - datasets
    - evaluate
    - pip
    - pytest
    - scipy
    - scikit-learn
    - transformers
    - tqdm

about:
  home: https://github.com/huggingface/accelerate
  doc_url: https://huggingface.co/docs/accelerate
  summary: Training loop of PyTorch without boilerplate code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
